run();

async function run() {
    try {
    }
    catch(err) {
        console.log("ERROR: " + err.message);
    }
}
